### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/UVPlugin-rdfToCKAN#10] opened 2015-07-10 11:13 UTC
I have a pipeline http://www.filedropper.com/showdownload.php/sap-protectedsites exported by odn 1.0.3 and imported in 1.1.0

After run I get an exception in gui

```

u.unifiedviews.dpu.DPUException DPU.innerExecute throws runtime exception.
   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:123)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException null
   ... 4 common frames omitted   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
```

**Comment by Jan-Marcek** [comment] 2015-07-10 11:31
It is not because import/exported. DPU doesn't work even with  simple pipeline.
version: uv-l-rdfToCkan-1.1.0-20150625.235338-13.jar

**Comment by ghost** [comment] 2015-07-10 11:32
In the stacktrace threre is "filestockan"...

**Comment by Jan-Marcek** [comment] 2015-07-10 11:33
updated.

**Comment by Jan-Marcek** [comment] 2015-07-10 11:41
simple pipeline: http://www.filedropper.com/test_26

**Comment by ghost** [comment] 2015-07-14 07:20
the stacktrace now does not include cause exception. only the outer one from helpers (AbstractDpu). There is also "Caused by" section aftewards, isn't it?

**Comment by Jan-Marcek** [comment] 2015-07-21 07:17
@mkl-eea-sk  Have you tried to import pipeline above? I haven't seen any result of it.

**Comment by ghost** [comment] 2015-07-22 06:16
Fixed in https://github.com/OpenDataNode/UVPlugin-rdfToCKAN/commit/ba632e91b4edc2996f0ee8efc12bcf85d9907a6a

**Comment by ghost** [comment] 2015-07-22 06:17
Wrong usage of DPU , prepend rdfToVirtuoso before using rdfToCkan or use rdfToVirtuosoAndCkan.

**Closed as completed** 2015-07-22 06:17 UTC
Labels: bug, priority: High, fixed

**Comment by skrchnavy** [comment] 2015-07-22 06:50
cherrypicked to release branch (4b59ea2b363f8f3802c00f64e22e292d75ac2896)
